### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by kilchenmann** [dasch-swiss/sipi#322]
Could we add a link to the Sipi Github repository somewhere in the documentation (preferably at the top of the page)?

Additional I had the following errors during installation and build. I was able to solve them, so we should update the documentation:

- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
  - Solved with `brew install pkg-config` --> update `Prerequisites / macOs`
<br>

- Error: invalid option: --with-openjpeg
  - Solved with brew `install imagemagick` without the option `--with-openjpeg`  because imagemagick depends on openjpeg. But not sure if this is correct now. https://formulae.brew.sh/formula/imagemagick
<br>

And we should remove the section "Generating Documentation" because it's not up to date. The folder manual doesn't exist anymore since we use mkdocs for the documentation.

**Comment by julsraemy** [comment]
@kilchenmann I'm currently looking at updating the documentation. Has the above issues been addressed?

**Comment by kilchenmann** [comment]
> @kilchenmann I'm currently looking at updating the documentation. Has the above issues been addressed?

No, I think this is not done yet. You're welcome to update the sipi docs 😉

**Comment by kilchenmann** [comment]
> Could we add a link to the Sipi Github repository somewhere in the documentation (preferably at the top of the page)?


This could be done in mkdocs configuration by adding / updating the following lines:

```yaml
repo_url: https://github.com/dasch-swiss/sipi
repo_name: dasch-swiss/sipi
...
theme:
  name: material
  logo: 'assets/icons/dasch-icon-white.svg'
  favicon: 'assets/icons/dasch-favicon.ico'
  icon:
    repo: fontawesome/brands/github
...
```

Similar to the [DSP-UI documentation](https://dasch-swiss.github.io/dsp-ui-lib/)
